name: Flutter CI/CD

# ワークフローをトリガーするイベントを定義
'on':
  push:
    branches:
      - main  # mainブランチへのpush時に実行
  pull_request:
    branches:
      - main  # mainブランチへのPR作成時に実行

# ワークフロー内のジョブを定義
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # ジョブが実行される仮想環境を指定
    steps:
      - name: Checkout  # リポジトリのコードをチェックアウト
        uses: actions/checkout@v4
        
      - name: Flutter setting  # Flutterのセットアップ
        uses: subosito/flutter-action@v2
        with:
          channel: stable  #安定板
          cache: true

      #インストール＆ビルド    
      - name: "Install and Build" 
        run: |
          flutter pub get
          flutter test
          flutter build apk --release
          flutter build web

      ## ビルドしたapkをgithub Actionsアップロード(デプロイ)    
      - name: "Deploy"
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
